In [1]:
import pandas as pd

In [2]:
fake_df = pd.read_csv('fake_reviews.csv')

In [3]:
fake_df

,Unnamed: 0,User review,Review date,Star review,Text length,Has media,Has answer,Written by bot
0,0,"Отличный товар, всем рекомендую! Качество на в...",2024-09-30,5,66,True,1,1
1,1,Превзошло все мои ожидания! Советую всем друзьям.,2024-09-29,5,51,False,1,1
2,2,"Купил и остался доволен, за такие деньги лучше...",2024-09-28,5,54,False,1,1
3,3,"Очень хорошее качество, всем советую этот прод...",2024-09-27,5,54,True,0,1
4,4,"Заказываю не первый раз, всегда всё отлично.",2024-09-26,5,49,False,1,1
...,...,...,...,...,...,...,...,...
94,94,"Все супер, продукт на высоте.",2024-06-28,5,38,True,1,1
95,95,"Товар рекомендую, все на высшем уровне.",2024-06-27,5,44,False,1,1
96,96,"Не ожидал такого высокого качества, покупкой д...",2024-06-26,5,52,True,1,1
97,97,"Все замечательно, продукт оправдал ожидания.",2024-06-25,5,48,False,1,1
98,98,"Рекомендую товар, куплю еще раз.",2024-06-24,5,37,True,1,1