In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('main_df.csv')

In [3]:
df

,Unnamed: 0,User review,Review date,Star review,Text length,Has media,Has answer,Written by bot
0,0.0,Достоинства\r\n все устроило нормальная ...,2024-10-09,5,54,0,0,0
1,1.0,"Шикарная, начиталась отзывы, но рискнула, что ...",2024-10-09,5,195,0,0,0
2,2.0,Дочке понравилась,2024-10-09,5,17,0,0,0
3,3.0,"Пока не одевала ,но то что хотела",2024-10-09,5,33,0,0,0
4,4.0,Отличная куртка,2024-10-09,5,15,0,0,0
...,...,...,...,...,...,...,...,...
1792,94.0,"Все супер, продукт на высоте.",2024-06-28,5,38,1,1,1
1793,95.0,"Товар рекомендую, все на высшем уровне.",2024-06-27,5,44,0,1,1
1794,96.0,"Не ожидал такого высокого качества, покупкой д...",2024-06-26,5,52,1,1,1
1795,97.0,"Все замечательно, продукт оправдал ожидания.",2024-06-25,5,48,0,1,1
1796,98.0,"Рекомендую товар, куплю еще раз.",2024-06-24,5,37,1,1,1